spring:
  application:
    name: kick-scooter-gateway

  cloud:
    gateway:
      default-filters:
        - StripPrefix=1
      routes:
        - id: payment-service
          uri: lb://payment-service/kick-scooter-payment
          predicates:
            - Path=/payment-service/kick-scooter-payment/**
        - id: vehicle-service
          uri: lb://vehicle-service/kick-scooter-vehicle
          predicates:
            - Path=/vehicle-service/kick-scooter-vehicle/**
        - id: trip-service
          uri: lb://trip-service/kick-scooter-trip
          predicates:
            - Path=/trip-service/kick-scooter-trip/**
        - uri: lb://messaging-service/kick-scooter-messaging
          predicates:
            - Path=/messaging-service/kick-scooter-messaging/**
        - id: identity-service
          uri: lb://identity-service/kick-scooter-identity
          predicates:
            - Path=/identity-service/kick-scooter-identity/**
        - id: simulation-service
          uri: lb://simulation-service
          predicates:
            - Path=/simulation-service/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
            exposedHeaders:
              - Authorization

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER}/eureka/

logging:
  file:
    path: /var/log/gateway
